spring:
  cloud:
    nacos:
      discovery:
        server-addr: tc.zhanghanlin.club:8848
  application:
    name: rainbow-discovery-test
server:
  port: 8081
rainbow:
  env:
    gray:
      enable: true
